[package]
name = "xash_master_api"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.29", features = ["full"] }
serde = { version = "1.0", features = ["derive"] }
actix-web = "4.3"
futures = "0.3"
format-bytes = "0.2"